ports:
  - port: 8000
tasks:
  - before: nvm i lts/fermium && nvm alias default lts/fermium
    init: npm install && npm run build
    command: npm run start
vscode:
  extensions:
    - jpoissonnier.vscode-styled-components
    - paulmolluzzo.convert-css-in-js
